#!/bin/sh

# Concatenates multiple descriptions of annotations into a single one.

SCENE_LIB=$(dirname $0)
WORKSPACE=$SCENE_LIB/..
JAVAC_JAR=${JAVAC_JAR:-${SCENE_LIB}/../../jsr308-langtools/dist/lib/javac.jar}

export CLASSPATH=$SCENE_LIB/bin:$WORKSPACE/annotation-file-utilities/lib/asm-5.0.4.jar:$WORKSPACE/annotation-file-utilities/lib/plume-core.jar:$CLASSPATH
java annotations.tools.Anncat "$@"
